### ISSUE TITLE
error after opening 'search' and then doing escape

### ISSUE THREAD

**Issue by MartijnKaijser** [paddycarey/plugin.video.mmabrowser#2]
19:33:06 T:7136   DEBUG: ------ Window Init (DialogProgress.xml) ------
19:33:06 T:6556   ERROR: Traceback (most recent call last):
                                              File "D:\XBMC Eden\portable_data\addons\plugin.video.mms\default.py", line 82, in <module>
                                                searchAll()
                                              File "D:\XBMC Eden\portable_data\addons\plugin.video.mms\resources\lib\navigation.py", line 61, in searchAll
                                                for event in dbops.searchEvents(searchStr):
                                              File "D:\XBMC Eden\portable_data\addons\plugin.video.mms\resources\lib\databaseops.py", line 82, in searchEvents
                                                cur.execute("SELECT DISTINCT eventID, title, promotion, date, venue, city FROM events WHERE (eventID LIKE '%s' OR title LIKE '%s' OR promotion LIKE '%s' OR date LIKE '%s' OR venue LIKE '%s' OR city LIKE '%s') ORDER BY date" % ("%" + searchStr + "%", "%" + searchStr + "%", "%" + searchStr + "%", "%" + searchStr + "%", "%" + searchStr + "%", "%" + searchStr + "%"))
                                            TypeError: cannot concatenate 'str' and 'NoneType' objects
19:33:06 T:6556    INFO: -->End of Python script error report<--

**Comment by paddycarey** [comment]
oops, how'd i miss that? should be an easy fix, i'll get it when i get home

**Comment by MartijnKaijser** [comment]
That's why i'm here.
To find bugs :D
